apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-putp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pdex-tenant/rhtap-demo-app/hacbs-test-project-putp@sha256:d7d4fbbbd45125c5e5a231a8dd7cfc230a2b87e2bb30d8eac84fab2730b97dd8
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
